# Lingfei Wang, 2022. All rights reserved.
name: Install with anaconda & install checks through conda scripts

inputs:
  package:
    description: Package name and optionally version to install
    required: true
  cuda-version:
    description: cudatoolkit version within anaconda. If omited, install CPU version instead.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install
      shell: bash
      run: |
        echo '::group::Installation'
        if [ "a${{ inputs.cuda-version }}" == "a" ]; then pkgadd="cpuonly"; else pkgadd="cudatoolkit=${{ inputs.cuda-version }}"; fi
        conda create -y -n dictys -c conda-forge python=3.9 mamba
        . activate dictys
        mamba install -y -c lingfeiwang -c bioconda -c conda-forge -c pytorch ${{ inputs.package }} $pkgadd
        echo '::endgroup::'
    - name: Test python version
      shell: bash
      run: |
        set -e -o pipefail
        . activate dictys
        v="${{ inputs.python-version }}"
        v="Python ${v/./[.]}"
        python --version
        python --version 2>&1 | grep "$v"
        python3 --version
        python3 --version 2>&1 | grep "$v"
        conda deactivate
    - name: Test run
      shell: bash
      run: |
        set -e -o pipefail
        . activate dictys
        python -m dictys -h
        python -m dictys preproc selects_rna -h
        conda deactivate
