name: Translate Zenodo URL to follow the latest DOI version 

inputs:
  url:
    description: Zenodo URL to follow/translate
    required: true

outputs:
  url:
    description: Final URL
    value: ${{ steps.translate.outputs.url }}
    
runs:
  using: composite
  steps:
    - name: Translate
      id: translate
      shell: bash
      run: |
        set -eo pipefail
        s0='${{ inputs.url }}'
        s1="$(curl -Ls -o /dev/null -w %{url_effective} "$s0")"
        s2="$s1/${s0#http[s]*://zenodo.org/record/[^/]*/}"
        echo "Old URL: $s0"
        echo "New URL: $s2"
        echo "::set-output name=url::$s2"
