name: CI for network inference tests on container

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'setup.py'
      - 'src/**'
      - 'bin/**'
      - 'utils/docker/**'
      - '.github/workflows/ci-inference-container.yml'
      - '.github/actions/zenodo-url-translate/**'
      - '.github/actions/inference-test-dataset/**'
      - '.github/scripts/inference-test-dataset.py' 

jobs:
  test-blood1:
    name: Blood static network unit tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-cpu-pretest:dev
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Get dataset URL
      id: zenodo-url-translate
      uses: ./.github/actions/zenodo-url-translate
      with:
        url: https://zenodo.org/record/6858494/files/inference-blood1.tar.xz?download=1
    - name: Test dataset
      uses: ./.github/actions/inference-test-dataset
      with:
        url: ${{ steps.zenodo-url-translate.outputs.url }}
        test-path: ci_testspace
        makefile: test_static.mk
        expected-folder: test/tmp_static_expected
        actual-folder: test/tmp_static
        expected-h5: test/output/static_expected.h5
        actual-h5: test/output/static.h5
        makefile-params: '{"ENVMODE": "none", "NTH": "2", "DEVICE": "cpu", "GENOME_MACS2": "hs", "JOINT": "0", "KPARAMS-NETWORK-RECONSTRUCT+": " --nstep 10 --nstep_report 3"}'
        exclusions: 'reads.bam reads.bai net_weight.tsv.gz net_covfactor.tsv.gz net_meanvar.tsv.gz net_loss.tsv.gz net_stats.tsv.gz'
        
