name: CI installation

on: [push]

jobs:
  install-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Test install script agreement between README.rst and doc/scripts/install-cpu.sh
      run: |
        # Install in README.rst (indented in Installation section)
        linestart=$(grep -n '^Installation' README.rst | awk -F: '{print $1}' | head -n 1)
        lineend=$(tail -n +$(( linestart + 2 )) README.rst  | grep -n '^==' | awk -F: '{print $1}' | head -n 1)
        linestart2=$(tail -n +$linestart README.rst | head -n $lineend | grep -n '^.. code-block::' | awk -F: '{print $1}' | head -n 1)
        s1="$(tail -n +$linestart README.rst | head -n $lineend | tail -n +$linestart2 | grep '^[[:blank:]]' | sed 's/^[[:space:]]*//g')"
        echo "$s1"
        # Install in doc/scripts/install-cpu.sh (after first empty line)
        slinestart=$(grep -n '^$' doc/scripts/install-cpu.sh | awk -F: '{print $1}' | head -n 1)
        s2="$(tail -n +$(( slinestart + 1 )) doc/scripts/install-cpu.sh)"
        s2="${s2/\$PYTHONVERSION_CONDA/3.8}"
        echo "$s2"
        cmp <(echo "$s1") <(echo "$s2")
    - name: Test install
      run: PYTHONVERSION_CONDA=${{ matrix.python-version }} . doc/scripts/install-cpu.sh
    - name: Test python version
      run: |
        set -e -o pipefail
        . activate dictys_env_name
        v="${{ matrix.python-version }}"
        v="Python ${v/./[.]}"
        python --version
        python --version 2>&1 | grep "$v"
        conda deactivate
