name: Weekly test for installation from short URL

on:
  schedule:
    - cron: '20 7 * * 1'

jobs:
  install-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Test identical install script
      run: |
        # Install command in README.rst (indented in Installation section)
        # Get first code-block in section Installation
        linestart=$(grep -n '^Installation' README.rst | awk -F: '{print $1}' | head -n 1)
        lineend=$(tail -n +$(( linestart + 2 )) README.rst  | grep -n '^==' | awk -F: '{print $1}' | head -n 1)
        linestart2=$(tail -n +$linestart README.rst | head -n $lineend | grep -n '^.. code-block::' | awk -F: '{print $1}' | head -n 1)
        lineend2=$(tail -n +$linestart README.rst | head -n $lineend | tail -n +$(( linestart2 + 1 )) | grep -n '^.. code-block::' | awk -F: '{print $1}' | head -n 1)
        s1="$(tail -n +$linestart README.rst | head -n $lineend | tail -n +$linestart2 | head -n $lineend2 | grep '^[[:blank:]]' | sed 's/^[[:space:]]*//g')"
        echo "$s1"
        cmp <(echo "$s1") <(echo "wget https://tinyurl.com/dictys -O - | bash")

  install-linux:
    runs-on: ubuntu-latest
    needs: install-script
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Test install
      run: |
        echo '::group::Test install output'
        wget https://tinyurl.com/dictys -O - | bash
        echo '::endgroup::'
