name: Installation script test

on:
  schedule:
    - cron: '20 7 * * 1'
  push:
    paths:
      - '.github/workflows/ci-install.yml'
      - README.rst
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit or branch to run action on'
        required: true
        default: 'dev2'

jobs:
  install-script-bash:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.run.outputs.run }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref || github.devent.push.ref || github.event.repository.default_branch }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Obtain install script
      id: run
      run: |
        # Install command in README.rst (indented in Installation section)
        # Get first code-block in section Installation
        linestart=$(grep -n '^Installation' README.rst | awk -F: '{print $1}' | head -n 1)
        lineend=$(tail -n +$(( linestart + 2 )) README.rst  | grep -n '^==' | awk -F: '{print $1}' | head -n 1)
        linestart2=$(tail -n +$linestart README.rst | head -n $lineend | grep -n '^With .*bash script' | awk -F: '{print $1}' | head -n 1)
        linestart=$(( linestart + linestart2 ))
        lineend=$(tail -n +$(( linestart + 2 )) README.rst | head -n $lineend | grep -n '^--' | awk -F: '{print $1}' | head -n 1)
        linestart2=$(tail -n +$linestart README.rst | head -n $lineend | grep -n '^.. code-block::' | awk -F: '{print $1}' | head -n 1)
        lineend2=$(tail -n +$linestart README.rst | head -n $lineend | tail -n +$(( linestart2 + 1 )) | grep -n '^.. code-block::' | awk -F: '{print $1}' | head -n 1)
        s1="$(tail -n +$linestart README.rst | head -n $lineend | tail -n +$linestart2 | head -n $lineend2 | grep '^[[:blank:]]' | sed 's/^[[:space:]]*//g')"
        echo "$s1"
        cmp <(echo "$s1") <(echo "wget https://tinyurl.com/dictys -O - | bash") || exit 1
        echo "::set-output name=run::$s1"
    
  install-linux-bash:
    runs-on: ubuntu-latest
    needs: install-script-bash
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Test install
      run: |
        echo '::group::Test install output'
        ${{needs.install-script-bash.outputs.run}}
        echo '::endgroup::'

  install-script-conda:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.run.outputs.run }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref || github.devent.push.ref || github.event.repository.default_branch }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Obtain install script
      id: run0
      run: |
        # Install command in README.rst (indented in Installation section)
        # Get first code-block in section Installation
        linestart=$(grep -n '^Installation' README.rst | awk -F: '{print $1}' | head -n 1)
        lineend=$(tail -n +$(( linestart + 2 )) README.rst  | grep -n '^==' | awk -F: '{print $1}' | head -n 1)
        linestart2=$(tail -n +$linestart README.rst | head -n $lineend | grep -n '^With .*conda$' | awk -F: '{print $1}' | head -n 1)
        linestart=$(( linestart + linestart2 ))
        lineend=$(tail -n +$(( linestart + 2 )) README.rst | head -n $lineend | grep -n '^--' | awk -F: '{print $1}' | head -n 1)
        linestart2=$(tail -n +$linestart README.rst | head -n $lineend | grep -n '^.. code-block::' | awk -F: '{print $1}' | head -n 1)
        lineend2=$(tail -n +$linestart README.rst | head -n $lineend | tail -n +$(( linestart2 + 1 )) | grep -n '^.. code-block::' | awk -F: '{print $1}' | head -n 1)
        s1="$(tail -n +$linestart README.rst | head -n $lineend | tail -n +$linestart2 | head -n $lineend2 | grep '^[[:blank:]]' | sed 's/^[[:space:]]*//g')"
        echo "run<<EOF" >> $GITHUB_ENV
        echo "$s1" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - id: run
      uses: actions/github-script@v5
      with:
        script: |
          core.setOutput("run", `${{ env.run }}`);
    
  install-linux-conda:
    runs-on: ubuntu-latest
    needs: install-script-conda
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Test install
      run: |
        echo '::group::Test install output'
        ${{ needs.install-script-conda.outputs.run }}
        echo '::endgroup::'

  install-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9",""]
        cuda-version: ["11.3",""]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref || github.devent.push.ref || github.event.repository.default_branch }}
    - name: Install
      uses: ./.github/actions/install
      with:
        python-version: ${{ matrix.python-version }}
        cuda-version: ${{ matrix.cuda-version }}
